model_params:
  name: 'diffusion'
  num_timesteps: 100

exp_params:
  LR: 0.0001
  scheduler_gamma: 0.95
  batch_size: 16

trainer_params:
  gpus: [0]
  max_epochs: 2000

logging_params:
  save_dir: "logs/"
  name: "ddpm"
