model_params:
    name: 'diffusion'
    num_timesteps: 100
  
exp_params:
  LR: 0.0001
  scheduler_gamma: 0.95
  batch_size: 16
  S1func: rarest #random, rarest, frechet, inception, loss, none
  k: 5000 #S1 size

trainer_params:
  gpus: [0]
  max_epochs: 300

logging_params:
  save_dir: "logs/"
  name: "rarest155"
  